2021-03-13 14:25:04,850 INFO    MainThread:24179 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:25:04,850 INFO    MainThread:24179 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:25:04,850 INFO    MainThread:24179 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_142504-v6gl384t/logs/debug.log
2021-03-13 14:25:04,851 INFO    MainThread:24179 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_142504-v6gl384t/logs/debug-internal.log
2021-03-13 14:25:04,851 INFO    MainThread:24179 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb8d276aa60>
2021-03-13 14:25:04,851 INFO    MainThread:24179 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:25:04,851 INFO    MainThread:24179 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:25:04,851 INFO    MainThread:24179 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 1pwudvow
2021-03-13 14:25:04,853 INFO    MainThread:24179 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/1pwudvow
2021-03-13 14:25:04,853 INFO    MainThread:24179 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-13 14:25:04,854 INFO    MainThread:24179 [wandb_run.py:_restore():1418] restore
2021-03-13 14:25:05,146 INFO    MainThread:24179 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 591
  total_bytes: 591
}

2021-03-13 14:25:07,157 INFO    MainThread:24179 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3997
  total_bytes: 3997
}

2021-03-13 14:25:08,402 INFO    MainThread:24179 [wandb_run.py:_show_summary():1723] rendering summary
2021-03-13 14:25:08,403 INFO    MainThread:24179 [wandb_run.py:_show_history():1761] rendering history
2021-03-13 14:25:08,404 INFO    MainThread:24179 [wandb_run.py:_show_files():1790] logging synced files
2021-03-13 14:25:08,409 INFO    MainThread:24179 [wandb_init.py:init():416] starting backend
2021-03-13 14:25:08,410 INFO    MainThread:24179 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-13 14:25:08,412 INFO    MainThread:24179 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 14:25:08,417 INFO    MainThread:24179 [backend.py:ensure_launched():127] started backend process with pid: 24336
2021-03-13 14:25:08,423 INFO    MainThread:24179 [wandb_init.py:init():421] backend started and connected
2021-03-13 14:25:08,437 INFO    MainThread:24179 [wandb_init.py:init():461] updated telemetry
2021-03-13 14:25:08,438 INFO    MainThread:24179 [wandb_init.py:init():480] communicating current version
2021-03-13 14:25:09,171 INFO    MainThread:24179 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 14:25:09,173 INFO    MainThread:24179 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 14:25:09,444 INFO    MainThread:24179 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 14:25:11,116 INFO    MainThread:24179 [wandb_run.py:_console_start():1476] atexit reg
2021-03-13 14:25:11,117 INFO    MainThread:24179 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-13 14:25:11,117 INFO    MainThread:24179 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-13 14:25:11,117 INFO    MainThread:24179 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-13 14:25:11,117 INFO    MainThread:24179 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 14:25:11,119 INFO    MainThread:24179 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:25:11,119 INFO    MainThread:24179 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:25:12,176 INFO    MainThread:24179 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:25:45,198 INFO    MainThread:24179 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:25:45,198 INFO    MainThread:24179 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:25:45,202 INFO    MainThread:24179 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:25:45,343 INFO    MainThread:24179 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:25:45,343 INFO    MainThread:24179 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:26:27,095 INFO    MainThread:24179 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:26:27,104 INFO    MainThread:24179 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:26:27,104 INFO    MainThread:24179 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:26:27,104 INFO    MainThread:24179 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_142627-w1olfiq1/logs/debug.log
2021-03-13 14:26:27,105 INFO    MainThread:24179 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_142627-w1olfiq1/logs/debug-internal.log
2021-03-13 14:26:27,105 INFO    MainThread:24179 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:26:27,105 INFO    MainThread:24179 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:26:27,105 INFO    MainThread:24179 [wandb_init.py:init():387] re-initializing run, found existing run on stack: v6gl384t
2021-03-13 14:26:27,107 INFO    MainThread:24179 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/v6gl384t
