2021-03-13 14:36:35,797 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:36:35,797 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_143635-112j2tj7/logs/debug.log
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_143635-112j2tj7/logs/debug-internal.log
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 1qtfnwsg
2021-03-13 14:36:35,799 INFO    MainThread:24441 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/1qtfnwsg
2021-03-13 14:36:35,799 INFO    MainThread:24441 [jupyter.py:save_history():320] not saving jupyter history
2021-03-13 14:36:35,800 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:36:35,800 INFO    MainThread:24441 [wandb_init.py:_jupyter_teardown():266] cleaning up jupyter logic
2021-03-13 14:36:35,800 INFO    MainThread:24441 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-13 14:36:35,800 INFO    MainThread:24441 [wandb_run.py:_restore():1418] restore
2021-03-13 14:36:36,063 INFO    MainThread:24441 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 591
  total_bytes: 591
}

2021-03-13 14:36:38,073 INFO    MainThread:24441 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5112
  total_bytes: 5112
}

2021-03-13 14:36:39,322 INFO    MainThread:24441 [wandb_run.py:_show_summary():1723] rendering summary
2021-03-13 14:36:39,322 INFO    MainThread:24441 [wandb_run.py:_show_history():1761] rendering history
2021-03-13 14:36:39,324 INFO    MainThread:24441 [wandb_run.py:_show_files():1790] logging synced files
2021-03-13 14:36:39,328 INFO    MainThread:24441 [wandb_init.py:init():416] starting backend
2021-03-13 14:36:39,329 INFO    MainThread:24441 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-13 14:36:39,331 INFO    MainThread:24441 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 14:36:39,340 INFO    MainThread:24441 [backend.py:ensure_launched():127] started backend process with pid: 24532
2021-03-13 14:36:39,345 INFO    MainThread:24441 [wandb_init.py:init():421] backend started and connected
2021-03-13 14:36:39,363 INFO    MainThread:24441 [wandb_init.py:init():461] updated telemetry
2021-03-13 14:36:39,363 INFO    MainThread:24441 [wandb_init.py:init():480] communicating current version
2021-03-13 14:36:40,235 INFO    MainThread:24441 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 14:36:40,237 INFO    MainThread:24441 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 14:36:40,568 INFO    MainThread:24441 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 14:36:42,318 INFO    MainThread:24441 [wandb_run.py:_console_start():1476] atexit reg
2021-03-13 14:36:42,319 INFO    MainThread:24441 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-13 14:36:42,319 INFO    MainThread:24441 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-13 14:36:42,319 INFO    MainThread:24441 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-13 14:36:42,320 INFO    MainThread:24441 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 14:40:06,923 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:40:06,923 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:40:06,923 INFO    MainThread:24441 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144006-32qxqh5k/logs/debug.log
2021-03-13 14:40:06,923 INFO    MainThread:24441 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144006-32qxqh5k/logs/debug-internal.log
2021-03-13 14:40:06,924 INFO    MainThread:24441 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fcce1db0a00>
2021-03-13 14:40:06,924 INFO    MainThread:24441 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:40:06,925 INFO    MainThread:24441 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:40:06,925 INFO    MainThread:24441 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 112j2tj7
2021-03-13 14:40:06,927 INFO    MainThread:24441 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/112j2tj7
